#  to set up the app itself
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aic-app
  template:
    metadata:
      labels:
        app: aic-app
    spec:
      containers:
      - name: nginx
        image: lothen123/aic-app
        ports:
        - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
#  to set up the service for the app 
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: aic-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP

